---
output: hugodown::md_document
title: "Books by Danielle Navarro"
type: "page"
summary: "Learning statistics with R and other books I've written"
author: ""
tags: []
date: 2020-09-02
---

# Books

It has come to my attention that I am in fact the author of multiple books.

> *"A book is a medium for recording information in the form of writing or images, typically composed of many pages bound together and protected by a cover. The technical term for this physical arrangement is codex."* --Wikipedia


## Learning Statistics with R

From 2011 to 2015 I taught an introductory statistics class using R and I wrote my own lecture notes. It got a little out of hand, turning into a 600 page book that is freely available under a CC BY-SA 4.0 licence at [learningstatisticswithr.com](https://learningstatisticswithr.com). It covers the basics of psychological research methods, R programming, data wrangling, descriptive statistics, R graphics, orthodox and Bayesian inference, t-tests, chi-square tests, factorial ANOVA and multiple regression in a friendly (and I hope helpful) way. 

To my surprise, the book has been rather popular, and has been adapted in several ways. David Foxcroft adapted it to create a [Jamovi version](https://doi.org/10.24384/hgc3-7p15), and Tom Faulkenberry adapted *that* to create a [JASP version](https://learnstatswithjasp.com/). Jean-Marc Meunier was kind enough to make a [French translation](https://jmeunierp8.github.io/ManuelJamovi/) of the Jamovi book, which is so cool, and I've heard rumours that there are [Japanese](https://bookdown.org/sbtseiji/lswjamoviJ/), Spanish and Turkish translations in the works elsewhere. Because the creative commons licence allows more radical adaptations, there's also a really nice book on [Answering Questions with Data](https://crumplab.github.io/statistics/) by Matt Crump that uses parts of the material from the original book.



```{r, echo=FALSE}
statsbooks <- data.frame(
  link = c(
    "https://learningstatisticswithr.com",
    "https://doi.org/10.24384/hgc3-7p15",
    "https://learnstatswithjasp.com/"
  ),
  image = c(
    "lsr.png",
    "jamovi.png",
    "jasp.png"
  )
)

bs4cards::cards(
  data = statsbooks, 
  link = link, 
  image = image,
  layout = "image-only",
  border_radius = 0, 
  spacing = 4,
  width = 3
)
```


As yet, no-one has created a *Learning Statistics with an Abacus* adaptation. 


## ggplot2: Elegant Graphics for Data Analysis

The ggplot2 package is a system for declaratively specifying data visualisations, and is one of the most widely-used R packages. The book, available at [ggplot2-book.org](https://ggplot2-book.org), describes the underlying "grammar of graphics" that powers the package. Originally a sole author work by Hadley Wickham, the forthcoming 3rd edition adds Thomas Lin Pedersen and I as coauthors.


